sonar.organization=pueblandres
sonar.projectKey=pueblandres_purchase-reporting-api
sonar.projectName=purchase-reporting-api
sonar.sourceEncoding=UTF-8
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml