spring:
  application:
    name: purchase-reporting-api

  # Configuración inicial Oracle (descomentar y ajustar)
  # datasource:
  #   url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
  #   username: APP_USER
  #   password: APP_PASSWORD
  #   driver-class-name: oracle.jdbc.OracleDriver

mybatis:
  # Configuración base inicial MyBatis
  # mapper-locations: classpath:/mappers/**/*.xml
  # type-aliases-package: com.example.purchasereportingapi.domain
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080
