server:
  port: 9092
spring:
  application:
    name: purchase-reporting-api

  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: purchase_user
    password: purchase_pass
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.purchasereportingapi.report

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html